services:
  - type: web
    name: trading-backtest-api
    runtime: python3
    buildCommand: pip install --only-binary=all -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: MONGODB_URI
        value: "mongodb://localhost:27017/"
      - key: PIP_ONLY_BINARY
        value: ":all:"
    healthCheckPath: /
